### ISSUE TITLE
Change status type in PROJECTS

### ISSUE THREAD

**Issue by if2159** [if2159/ProjectManagementApplication#10]
STATUS_TYPE should refer to a reference table.

**Comment by MikeZBi** [comment]
So we can just a number for the status type like 1,2,3,4 or 5 and have another table
called STATUS, that has attributes status_id and status_desc (complete, in dev, QA, waiting, in review). Then we have a foreign key in PROJECTS that references a status_id from table STATUS?

**Comment by if2159** [comment]
Yes, I think we should have a auto increment STATUS_ID, a STATUS_DESCRIPTION as you said, and yes a foreign key in PROJECTS. I believe the table should be named STATUSES to stay in line with the style thus far.

**Comment by MikeZBi** [comment]
Has the changes made to github been made to the Database?
ie.  you added START_DATE for the table PROJECTS but its not on the Database

**Comment by if2159** [comment]
No they have not.

**Comment by MikeZBi** [comment]
Okay, I'll get on those changes aswell

**Comment by MikeZBi** [comment]
Added a reference table  with attributes: STATUS_ID AND STATUS_DESCRIPTION and changed the attribute: STATUS_TYPE to int not null in the table PROJECTS with FOREIGN KEY (STATUS_TYPE) REFERENCES STATUSES(STATUS_ID)
