### ISSUE TITLE
USERS ROLE should be changed

### ISSUE THREAD

**Issue by if2159** [if2159/ProjectManagementApplication#7]
ROLE should refer to another reference table.

**Comment by if2159** [comment]
This should be solved in a similar manner to issue #10.

**Comment by MikeZBi** [comment]
Did a similar thing like the STATUS_TYPE in the PROJECTS. The attribute ROLE is now a non null int, and has a constraint: FOREIGN KEY (ROLE) REFERENCES USERS_ROLES(ROLE_ID).

Where USERS_ROLES is the reference table, and ROLE_ID is auto increment, and ROLE_DESCRIPTION is a varchar(20) NOT NULL. 

If anyone wants to check over the tables USERS_ROLES and STATUSES please do and see if it looks okay.

**Comment by if2159** [comment]
Changes made, and DB updated.
